### ISSUE TITLE
Limit Rasengan on screento one rasengan per Naruto object.

### ISSUE THREAD

**Issue by thungp** [thungp/naruto-game#4]
If we eventually create Naruto clones,
each clone will be able to generate a rasengan.

**Comment by Dangerbotz** [comment]
I made it so that there would only be one rasengan on the screen at a time. If it goes off the screen, it dies, and only Naruto shooting them creates the rasengans. I don't know if this is the exact functionality you were looking for. We'll have to iterate through this one.

**Comment by thungp** [comment]
I think it is fine for now.  What I had in mind at some point was that Naruto has this Jutsu (move) call ed multiple Shadow Clone Jutsu where he can temporarily clone himself multiple times and each clone can create a rasengan and in our world launch it at an enemy.  https://www.youtube.com/watch?v=gSRNKS_vnIg (time 3:47) In the video clip all the narutos charge into enemy. Since we are doing oodama rasengan, narutos would just launch the rasengans.

**Comment by thungp** [comment]
I finally was able to check out your issue#3 branch. Tested out the the jump and limiting rasengan to one per screen and it looks great. I really love the jump, gravity affect and how you can move left or right when he floats down.
